#spring.application.name=customerservice
#server.port=8081
#
## Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/customer_service?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#
## Flyway Configuration
#spring.flyway.enabled=true
#spring.flyway.baseline-on-migrate=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.url=jdbc:mysql://localhost:3306/customer_service
#spring.flyway.user=root
#spring.flyway.password=password
#
#logging.level.org.flywaydb=DEBUG

server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}/${DB_NAME:customer_service}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    db:
      enabled: true # To include database health

  flyway:
    enabled: true
    locations: classpath:db/migration


