apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerservice-deployment
spec:
  selector:
    matchLabels:
      app: customerservice-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: customerservice-mysql
    spec:
      containers:
        - name: customerservice
          image: gokulkrishnanm97/customerservice-0.0.1:v3
          ports:
            - containerPort: 8081
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: customerdb
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: password
          livenessProbe: # Liveness probe to check if the container is healthy
            httpGet:
              path: /actuator/health # Correct path to the health endpoint
              port: 8081
            initialDelaySeconds: 30 # Time before starting liveness checks
            timeoutSeconds: 5       # Timeout for the probe
            periodSeconds: 15       # Interval between checks
            failureThreshold: 5     # Number of failures before restarting
          readinessProbe: # Readiness probe to check if the container is ready to serve traffic
            httpGet:
              path: /actuator/health # Correct path to the health endpoint
              port: 8081
            initialDelaySeconds: 20 # Time before starting readiness checks
            timeoutSeconds: 5       # Timeout for the probe
            periodSeconds: 10       # Interval between checks
            failureThreshold: 3     # Number of failures before marking as not ready
---
apiVersion: v1
kind: Service
metadata:
  name: customerservice-svc
spec:
  selector:
    app: customerservice-mysql
  ports:
    - protocol: "TCP"
      port: 8081 # The port that the service is running on in the cluster
      targetPort: 8081 # The port exposed by the service
  type: NodePort # Type of the service.
