server:
  port: 8083

spring:
  application:
    name: product-service
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        enabled: true
#        service-name: product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}/${DB_NAME:product_service}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect

#management:
#  server:
#    port: 8083 # Ensure the management endpoints run on the same port as the app
#  endpoints:
#    web:
#      exposure:
#        include: health,info # Expose only necessary endpoints
#  health:
#    db:
#      enabled: true # Include database health checks
#    defaults:
#      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration

